### ISSUE TITLE
bug: card width too big 

### ISSUE THREAD

**Issue by KjetilIN** [IT-Start-Gjovik/startgjovik_website#196]
# What?

![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/66110094/02544144-1d71-401f-9fce-7a8d42b4b6ad)

# How?
Set a max width for card

**Comment by KjetilIN** [comment]
@Mosazghi Up for it?

**Comment by Mosazghi** [comment]
I can take a look.
