### ISSUE TITLE
Redesign 'comming events' section

### ISSUE THREAD

**Issue by AbdiYus** [IT-Start-Gjovik/startgjovik_website#311]
Redesigning the comming events section of the main page: 

original: 
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/133913649/18d2ce32-c997-4b56-b420-47fc27aaa6d1)
New design:
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/133913649/8f64f9eb-22e9-4568-9035-a696f4e6d3c9)

**Comment by Mosazghi** [comment]
Fixed in #312
