### ISSUE TITLE
For bedrifter - new hero 

### ISSUE THREAD

**Issue by AbdiYus** [IT-Start-Gjovik/startgjovik_website#332]
## Old hero:
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/133913649/2e005636-fd50-44d5-a324-e55df7d60740)

## New hero:
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/133913649/c6a76b65-31c3-4a1c-88b7-4da5599eb3f7)

**Comment by Mosazghi** [comment]
For this the `FrontPage`component needs to have props as arguments (i.e. image (optional), headerText etc.). 
@Hannah-Sofie Could you look into that?

**Comment by AbdiYus** [comment]
I can make the prop since i need it for the hero section @Mosazghi  @Hannah-Sofie

**Comment by AbdiYus** [comment]
I've made it here #336

**Comment by AbdiYus** [comment]
Solved by #353
