### ISSUE TITLE
Update boardmembers 

### ISSUE THREAD

**Issue by Mosazghi** [IT-Start-Gjovik/startgjovik_website#371]
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/116307580/3b4be98d-7ef3-44ab-96bc-2c9c28811a84)
Need images.

**Comment by LoiueFragosoUwUr** [comment]
Hi

This issue caught my attention, I browsed online the members names. Nonetheless, I could not recognize anyone from the team, since there are very few results.

Thanks

**Comment by LoiueFragosoUwUr** [comment]
Could you send me the appropiate accounts, instagram accounts or whether accounts you want to take the images from? and I'll make the changes.

**Comment by LoiueFragosoUwUr** [comment]
I got It, I've found them

**Comment by LoiueFragosoUwUr** [comment]
Actually the link is the same in all cases, I don't get it. 
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/126754704/2a8bac1c-6a77-4c95-8bd3-621389879ae0)

**Comment by Mosazghi** [comment]
@LoiueFragosoUwUr  Appreciate for trying, but only internal maintainers have access to the CMS Sanity (where we store the pictures, infos and etc.)

**Comment by LoiueFragosoUwUr** [comment]
I understand
________________________________
De: Mosazghi ***@***.***>
Enviado: domingo, 31 de marzo de 2024 7:01
Para: IT-Start-Gjovik/startgjovik_website ***@***.***>
Cc: Luis Fernando Fragoso Carranza ***@***.***>; Mention ***@***.***>
Asunto: [ADVERTENCIA, MENSAJE EXTERNO] Re: [IT-Start-Gjovik/startgjovik_website] Update boardmembers (Issue #371)



ADVERTENCIA, REMITENTE EXTERNO
ESTE MENSAJE SE ORIGINÓ FUERA DE LOS SERVICIOS INSTITUCIONALES. NO HAGA CLIC EN ENLACES NI ABRA ARCHIVOS ADJUNTOS Y LO MAS IMPORTANTE NO PROPORCIONE INFORMACIÓN A MENOS QUE RECONOZCA AL REMITENTE Y TENGA CERTEZA QUE EL CONTENIDO ES SEGURO.


@LoiueFragosoUwUr<https://github.com/LoiueFragosoUwUr> Appreciate for trying, but only internal maintainers have access to the CMS Sanity (where we store the pictures, infos and etc.)
