### ISSUE TITLE
Improve background image quality for About Us and Events page 

### ISSUE THREAD

**Issue by Mosazghi** [IT-Start-Gjovik/startgjovik_website#375]
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/116307580/5cb25282-d76f-4fe9-996d-2a094fc1877e)
Either choose a new image or fix the styling.

**Comment by LoiueFragosoUwUr** [comment]
Hi! 

I am Luis Fernando, I've seen your issue, and found it worth solving.

**Comment by LoiueFragosoUwUr** [comment]
I've been checking out online for images related to community and entrepeneurism.

**Comment by LoiueFragosoUwUr** [comment]
I've seen this picture in your instagram profile, can I have access to it? 
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/126754704/87731ebe-999b-4492-bc7f-06b9e32b2512)

**Comment by Mosazghi** [comment]
Here you have it: 


![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/116307580/d2c7906f-da9a-42ec-a8e5-bd9d6c41bc99)

**Comment by LoiueFragosoUwUr** [comment]
got it!

over!  n.n


________________________________
De: Mosazghi ***@***.***>
Enviado: sábado, 23 de marzo de 2024 17:50
Para: IT-Start-Gjovik/startgjovik_website ***@***.***>
Cc: Luis Fernando Fragoso Carranza ***@***.***>; Comment ***@***.***>
Asunto: [ADVERTENCIA, MENSAJE EXTERNO] Re: [IT-Start-Gjovik/startgjovik_website] Improve background image quality for About Us and Events page (Issue #375)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>


ADVERTENCIA, REMITENTE EXTERNO
ESTE MENSAJE SE ORIGINÓ FUERA DE LOS SERVICIOS INSTITUCIONALES. NO HAGA CLIC EN ENLACES NI ABRA ARCHIVOS ADJUNTOS Y LO MAS IMPORTANTE NO PROPORCIONE INFORMACIÓN A MENOS QUE RECONOZCA AL REMITENTE Y TENGA CERTEZA QUE EL CONTENIDO ES SEGURO.


Here you have it:

0455BABD-728E-40B1-8346-CC30346C4788.jpeg (view on web)<https://github.com/IT-Start-Gjovik/startgjovik_website/assets/116307580/d2c7906f-da9a-42ec-a8e5-bd9d6c41bc99>

**Comment by LoiueFragosoUwUr** [comment]
It looks better 
![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/126754704/3ab17647-30ec-41b8-a5e1-0b1416456dfc)

**Comment by Mosazghi** [comment]
Make a PR

**Comment by LoiueFragosoUwUr** [comment]
Yes, I'll be making some adjustments to optimize the image placement, and I'll submit the pull request



________________________________
De: Mosazghi ***@***.***>
Enviado: domingo, 24 de marzo de 2024 7:03
Para: IT-Start-Gjovik/startgjovik_website ***@***.***>
Cc: Luis Fernando Fragoso Carranza ***@***.***>; Comment ***@***.***>
Asunto: [ADVERTENCIA, MENSAJE EXTERNO] Re: [IT-Start-Gjovik/startgjovik_website] Improve background image quality for About Us and Events page (Issue #375)

No suele recibir correos electrónicos de ***@***.*** Por qué esto es importante<https://aka.ms/LearnAboutSenderIdentification>


ADVERTENCIA, REMITENTE EXTERNO
ESTE MENSAJE SE ORIGINÓ FUERA DE LOS SERVICIOS INSTITUCIONALES. NO HAGA CLIC EN ENLACES NI ABRA ARCHIVOS ADJUNTOS Y LO MAS IMPORTANTE NO PROPORCIONE INFORMACIÓN A MENOS QUE RECONOZCA AL REMITENTE Y TENGA CERTEZA QUE EL CONTENIDO ES SEGURO.


Make a PR

**Comment by Mosazghi** [comment]
#379
