### ISSUE TITLE
Change Icon

### ISSUE THREAD

**Issue by KjetilIN** [IT-Start-Gjovik/startgjovik_website#74]
# What?
Change the icon for the website in the tab;

![image](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/66110094/2ad2a94b-8732-444c-afe5-d4af33b3f3f1)

# How?

Should only need to create a new `.ico` file and replace the favorite ` .ico` file.

**Comment by kurtmgray** [comment]
I'd love to handle this. Any particular icon you had in mind or would you like me to create one?

**Comment by KjetilIN** [comment]
@kurtmgray Hi! 
We need the icon to be the following image below. I am not sure how to get the best resolution. 
Feel free to try it out and also add a screenshot of the final result! Thanks for reaching out 👍

![NY start logo bilde](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/66110094/5d76c228-1090-46cc-93ea-8f1dec7b7816)

**Comment by VIRAT9358** [comment]
![changes](https://github.com/IT-Start-Gjovik/startgjovik_website/assets/74507238/f689a782-125f-4178-813a-e8dd9b47d9ba)

**Comment by kurtmgray** [comment]
This is my first open-source issue, so I hope you'll bear with me here. Please see the screenshot below. 
<img width="525" alt="Screenshot 2023-08-20 at 10 47 56 AM" src="https://github.com/IT-Start-Gjovik/startgjovik_website/assets/94031594/0b8f073b-f39c-402c-9c76-b6da3581cf6d">

Please advise any changes you'd like!

Per your instructions, I cloned the repo, created a branch, made the necessary changes, but don't have permission to push to the branch I created. Would you like me to fork the repo and make the PR from there?

**Comment by VIRAT9358** [comment]
Oooo @kurtmgray what a timing man damn...

**Comment by KjetilIN** [comment]
@kurtmgray Yes! Please make a PR. Your solution looks good! Thank you! 
Please provide a good description in the PR. (The PR template is wrong btw so provide your own description that you see fit! )

**Comment by KjetilIN** [comment]
Solved! #80
<img src="https://media0.giphy.com/media/muPMoA0DeqioNVjbri/giphy.gif"/>

**Comment by KjetilIN** [comment]
Solved with pr  #80 !
<img src="https://media0.giphy.com/media/muPMoA0DeqioNVjbri/giphy.gif"/>
