### ISSUE TITLE
Add organization number in the footer

### ISSUE THREAD

**Issue by KjetilIN** [IT-Start-Gjovik/startgjovik_website#77]
# What? 
Add the organization code in the footer. 
This is the number assigned to Start Gjøvik in "brønnøysundregisteret".

# How?
Figure out the standard for adding the number in the footer. 
How it should look, be written, and any laws related to this.

**Comment by VIRAT9358** [comment]
Can you explain more on organization code.

**Comment by KjetilIN** [comment]
@VIRAT9358 I removed the `good first issue` label. This requires some information that we do not have yet, and also look into the Norwegian law/standard for adding the organization number in the footer.
